apiVersion: v1
kind: Service
metadata:
  name: my2podapp-service
spec:
  selector:
    app: twopodapp
  ports:
  - protocol: "TCP"
    port: 6000
    targetPort: 5000
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: twopodapp-deloyment
spec:
  selector:
    matchLabels:
      app: twopodapp
  replicas: 2
  template:
    metadata:
      labels:
        app: twopodapp
    spec:
      containers:
      - name: my1stdocker
        image: ajitsrawat/my1stdocker:firsttry
        imagePullPolicy: Always 
        ports:
        - containerPort: 5000
      
      - name: alphabetprinter
        image: ajitsrawat/alphabetprinter:Latest
        imagePullPolicy: Always 
        ports:
        - containerPort: 5001  
    
