apiVersion: v1
kind: Service
metadata:
  name: my1stdocker-service
spec:
  selector:
    app: my1stdocker
  ports:
  - protocol: "TCP"
    port: 6000
    targetPort: 5000
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my1stdocker
spec:
  selector:
    matchLabels:
      app: my1stdocker
  replicas: 2
  template:
    metadata:
      labels:
        app: my1stdocker
    spec:
      containers:
      - name: my1stdocker
        image: my1stdocker:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5000